### ISSUE TITLE
Fails to run `ays mdupdate`

### ISSUE THREAD

**Issue by amrhassan** [Jumpscale/dockers#1]
Running `ays mdupdate` on a fresh image fails with the following output:
```bash
root@machine:~# docker run -it jumpscale/ubuntu1504 ays mdupdate
/usr/local/bin/jspython: 4: /usr/local/bin/jspython: source: not found
init jumpscale
createDir: /opt/code/github/jumpscale/ays_jumpscale7
git pull https://github.com/Jumpscale/ays_jumpscale7.git -> /opt/code/github/jumpscale/ays_jumpscale7
http
The authenticity of host 'github.com (192.30.252.128)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
E:Warning: Permanently added 'github.com,192.30.252.128' (RSA) to the list of known hosts.
E:Permission denied (publickey).
E:fatal: Could not read from remote repository.
E:
E:Please make sure you have the correct access rights
E:and the repository exists.
Traceback (most recent call last):
~   File "/usr/local/bin/ays", line 338, in <module>
    j.atyourservice.updateTemplatesRepo()
~   File "/usr/local/lib/python2.7/dist-packages/JumpScale/baselib/atyourservice/AtYourServiceFactory.py", line 104, in updateTemplatesRepo
    j.do.pullGitRepo(url=repo['url'], branch=branch)
~   File "/usr/local/lib/python2.7/dist-packages/JumpScale/InstallTools.py", line 1630, in pullGitRepo
    self.execute(cmd,timeout=600)
~   File "/usr/local/lib/python2.7/dist-packages/JumpScale/InstallTools.py", line 1090, in execute
    raise RuntimeError("Could not execute cmd:\n'%s'\nerr:\n%s"%(command,err))
~ RuntimeError: Could not execute cmd:
'cd /opt/code/github/jumpscale/ays_jumpscale7;git -c http.sslVerify=false pull origin ays_unstable'
err:
Warning: Permanently added 'github.com,192.30.252.128' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.


type/level: UNKNOWN/1
RuntimeError: Could not execute cmd:
'cd /opt/code/github/jumpscale/ays_jumpscale7;git -c http.sslVerify=false pull origin ays_unstable'
err:
Warning: Permanently added 'github.com,192.30.252.128' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Note that the first line of the output is `/usr/local/bin/jspython: 4: /usr/local/bin/jspython: source: not found` which sounds like another problem as well.

**Comment by muhamadazmy** [comment]
Please, use this repo for this issue https://github.com/Jumpscale/docker_ubuntu1504

**Comment by amrhassan** [comment]
Issues are disabled on https://github.com/Jumpscale/docker_ubuntu1504
