### ISSUE TITLE
Building 4_ubuntu1510_js8 fails

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/dockers#2]
Hi @abdulrahmantkhalifa, I just tried to build the 4_ubuntu1510_js8 docker image, which failed on installing urllib3-1.15, see below for more details

Can you help?

```
*ERROR***********************************************************************************
action: run                  runid:localhost            (ERROR)
    CuisineCore.run.pip3 install urllib3 --upgrade|
    path: /opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineCore.py
DOC:
    @param profile, execute the bash profile first
ERROR:
    could not execute echo  | sudo -S bash -c "pip3 install urllib3 --upgrade",OUT:
    Collecting urllib3
      Downloading urllib3-1.15.1-py2.py3-none-any.whl (92kB)
    Installing collected packages: urllib3
      Found existing installation: urllib3 1.14
        Uninstalling urllib3-1.14:
          Successfully uninstalled urllib3-1.14
    Successfully installed urllib3
    STDERR:
    Traceback (most recent call last):
      File "/usr/local/bin/pip3", line 11, in <module>
        sys.exit(main())
      File "/usr/local/lib/python3.5/dist-packages/pip/__init__.py", line 221, in main
        return command.main(cmd_args)
      File "/usr/local/lib/python3.5/dist-packages/pip/basecommand.py", line 252, in main
        pip_version_check(session)
      File "/usr/local/lib/python3.5/dist-packages/pip/utils/outdated.py", line 102, in pip_version_check
        installed_version = get_installed_version("pip")
      File "/usr/local/lib/python3.5/dist-packages/pip/utils/__init__.py", line 848, in get_installed_version
        working_set = pkg_resources.WorkingSet()
      File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 619, in __init__
        self.add_entry(entry)
      File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 675, in add_entry
        for dist in find_distributions(entry, True):
      File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1942, in find_eggs_in_zip
        if metadata.has_metadata('PKG-INFO'):
      File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1463, in has_metadata
        return self.egg_info and self._has(self._fn(self.egg_info, name))
      File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1824, in _has
        return zip_path in self.zipinfo or zip_path in self._index()
      File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1704, in zipinfo
        return self._zip_manifests.load(self.loader.archive)
      File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1644, in load
        mtime = os.stat(path).st_mtime
    FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.5/dist-packages/urllib3-1.14-py3.5.egg'
[Thu12 07:48] - ...lib/JumpScale/tools/actions/Action.py:749  - ERROR    -

******************************************************************************************

[Thu12 07:48] - ...lib/JumpScale/tools/actions/Action.py:621  - ERROR    - error in action: action: run                  runid:localhost       (ERROR)
    pip3 install urllib3 --upgrade
```

**Comment by abdulrahmantkhalifa** [comment]
FIXED in https://github.com/Jumpscale/dockers
